name: expense_lab
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.3
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
