name: expense_lab
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.3
  google_fonts: ^8.0.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.10.5
  drift_dev: ^2.30.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
